// Regenerate CONTENT-STATUS.md from the content tree.
//
//   node scripts/content-status.mjs
//
// Build-time only, never imported by build.js. The "pending" and "placeholder 3D"
// sections are derived from the content itself (`draft: true`, and any model3d
// pointing at the shared stand-in GLB), so the tracker cannot drift out of sync
// with what is actually shipping. The "validated deliveries" table above them is
// hand-maintained — add a row each time the client sends material.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const read = (sub) =>
  readdirSync(path.join(root, "content", sub))
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(path.join(root, "content", sub, f), "utf8")));

const objects = read("objects");
const people = read("people");

// Hand-maintained: one row per client delivery received.
const DELIVERIES = [
  ["2026-09-27", "Rizal as an Artist", "Introduction text (2 essays), 9 long-form articles, 23 object descriptions, credit sheet, 24 artworks × ~5 images, photogrammetry source for 4 works"],
  ["2026-09-27", "Rizal as a Scholar 2026", "4 portraits (Pardo de Tavera, Resurrección Hidalgo, Fr. Sanchez, Juan Luna) + credit sheet"],
];

const draftObjects = objects.filter((o) => o.draft).sort((a, b) => a.order - b.order);
const draftPeople = people.filter((p) => p.draft).sort((a, b) => a.order - b.order);
const placeholder3d = objects
  .filter((o) => o.model3d?.src === "placeholder-3d.glb")
  .sort((a, b) => a.order - b.order);

const artistObjects = objects.filter((o) => o.section === "artist");
const missingMeta = (field) => artistObjects.filter((o) => !o[field]).length;

const row = (cells) => `| ${cells.join(" | ")} |`;
const L = [];
L.push("# Content status");
L.push("");
L.push("_Generated by `node scripts/content-status.mjs` — re-run it after any content change._");
L.push("");
L.push("Tracks which parts of the exhibition carry client-validated material and what is");
L.push("still outstanding. Everything not listed as pending below is text the client has");
L.push("signed off on, reproduced verbatim.");
L.push("");

L.push("## Validated deliveries");
L.push("");
L.push(row(["Received", "Delivery", "Contents"]));
L.push(row(["---", "---", "---"]));
for (const d of DELIVERIES) L.push(row(d));
L.push("");

L.push("## Pending — awaiting client text");
L.push("");
L.push("Derived from `draft: true`. These records ship with their images and credits; the");
L.push("detail page shows a short “being prepared” note where the prose will go.");
L.push("");
if (draftObjects.length + draftPeople.length === 0) {
  L.push("_Nothing pending._");
} else {
  L.push(row(["Record", "Section", "Has", "Needs"]));
  L.push(row(["---", "---", "---", "---"]));
  for (const o of draftObjects) {
    L.push(row([`\`${o.id}\``, o.section, `${o.images.length} images, credit`, "description"]));
  }
  for (const p of draftPeople) {
    L.push(row([`\`${p.id}\``, p.section, "portrait, credit", "role + biography"]));
  }
}
L.push("");

L.push("## Outstanding client request — artwork catalogue fields");
L.push("");
L.push("The Artist delivery supplies no accession numbers or dimensions, and states");
L.push("materials/condition only inside the description prose. Artist detail pages");
L.push("therefore show fewer metadata rows than Ethnographer ones. Requesting a");
L.push("structured catalogue sheet closes the last gap to full parity.");
L.push("");
L.push(row(["Field", "Artist works missing it", "of"]));
L.push(row(["---", "---", "---"]));
for (const f of ["materials", "dimensions", "accession", "condition"]) {
  L.push(row([`\`${f}\``, String(missingMeta(f)), String(artistObjects.length)]));
}
L.push("");

L.push("## Placeholder 3D");
L.push("");
L.push("Photogrammetry was delivered as Agisoft Metashape source (`.psx`), not a");
L.push("web-ready model. These works are wired to the shared stand-in GLB so the 3D");
L.push("gallery slide and viewer are live; swapping in the real scan is a three-field");
L.push("edit (`src`, `poster`, `altText`) with no template change. See");
L.push("`scripts/models/README.md` for the Blender → gltf-transform pipeline.");
L.push("");
if (placeholder3d.length === 0) {
  L.push("_No placeholder models in use._");
} else {
  L.push(row(["Record", "Awaiting"]));
  L.push(row(["---", "---"]));
  for (const o of placeholder3d) L.push(row([`\`${o.id}\``, "optimised .glb (≤ 8 MB) + poster render"]));
}
L.push("");

L.push("## Translations");
L.push("");
L.push("Filipino and German copy already on the site is **AI-drafted and awaiting");
L.push("native-speaker review** before publication. English is the source of truth.");
L.push("");
L.push("Coverage below is measured from the content itself: a JSON field counts as");
L.push("translated when it carries `fil`/`de` keys, an essay when its");
L.push("`<slug>.fil.md` / `<slug>.de.md` sibling exists. Anything untranslated falls");
L.push("back to English at render — never a broken page.");
L.push("");

const essayDir = path.join(root, "content", "essays");
const essays = readdirSync(essayDir).filter((f) => f.endsWith(".md") && !/\.(fil|de)\.md$/.test(f));
const essayHas = (f, loc) => readdirSync(essayDir).includes(f.replace(/\.md$/, `.${loc}.md`));
const localized = (v) => typeof v === "object" && v !== null && "fil" in v && "de" in v;

const groups = [
  ["Essays", essays.map((f) => ({ id: f, done: essayHas(f, "fil") && essayHas(f, "de") })),
    (e) => e.id.startsWith("rizal-as-artist") || false],
];
const essayRows = essays.map((f) => ({ f, done: essayHas(f, "fil") && essayHas(f, "de") }));
const objRows = objects.map((o) => ({
  id: o.id, section: o.section,
  done: !o.description || localized(o.description),
}));
const peopleRows = people.map((p) => ({
  id: p.id, section: p.section,
  done: !p.bio || localized(p.bio),
}));

const pct = (done, total) => (total === 0 ? "—" : `${Math.round((done / total) * 100)}%`);
const tally = (rows) => [rows.filter((r) => r.done).length, rows.length];

const [ed, et] = tally(essayRows);
const artistObjs = objRows.filter((r) => r.section === "artist");
const otherObjs = objRows.filter((r) => r.section !== "artist");
const [aod, aot] = tally(artistObjs);
const [ood, oot] = tally(otherObjs);
const [pd, pt] = tally(peopleRows);

L.push(row(["Content set", "Translated", "Total", "Coverage"]));
L.push(row(["---", "---", "---", "---"]));
L.push(row(["Essays", String(ed), String(et), pct(ed, et)]));
L.push(row(["Object records — artist", String(aod), String(aot), pct(aod, aot)]));
L.push(row(["Object records — other sections", String(ood), String(oot), pct(ood, oot)]));
L.push(row(["Person records", String(pd), String(pt), pct(pd, pt)]));
L.push("");

const missingEssays = essayRows.filter((r) => !r.done).map((r) => r.f.replace(/\.md$/, ""));
if (missingEssays.length) {
  L.push("Essays still English-only on `/fil/` and `/de/`:");
  L.push("");
  for (const s of missingEssays) L.push(`- \`${s}\``);
  L.push("");
}

writeFileSync(path.join(root, "CONTENT-STATUS.md"), L.join("\n") + "\n");
console.log(
  `CONTENT-STATUS.md written — ${draftObjects.length} draft object(s), ` +
    `${draftPeople.length} draft person/people, ${placeholder3d.length} placeholder model(s)`,
);
